### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by IkeAlmighty** [IkeAlmighty/prework-study-guide#1]
# HTML

## User Story
As a prework student, 
I want the prework notes to be structured on a webpage
so I can easily find and read information

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, and Javascript with associated notes listed

**Comment by Nishant9771** [comment]
There are some Listed Websites where you can check once :

freecodecamp
MDN WEB
codecademy
coursera
w3school
or last you can explore any repositories regading that on github.
